CREATE TABLE COMMAND
(
    CONTEXT_ID         VARCHAR2(255 CHAR),
    CONTEXT            VARCHAR2(255 CHAR),
    CORRELATION_ID     VARCHAR2(255 CHAR),
    NODE_ID            NUMBER(1,0),
    REQUEST_PAYLOAD    BLOB NOT NULL,
    REQUEST_DATE_TIME  TIMESTAMP(6),
    RESPONSE_PAYLOAD   BLOB,
    RESPONSE_DATE_TIME TIMESTAMP(6),
    CHANGE_CONTROL_ID  NUMBER(9,0),
    CONSTRAINT COMMAND_PK PRIMARY KEY (CONTEXT_ID, CONTEXT, CORRELATION_ID, NODE_ID)
);

CREATE TABLE INITIAL_PAYLOAD
(
    ID                INTEGER NOT NULL,
    BALLOT_BOX_ID     VARCHAR2(255 CHAR) NOT NULL,
    ELECTION_EVENT_ID VARCHAR2(255 CHAR) NOT NULL,
    PAYLOAD           BLOB    NOT NULL,
    CHANGE_CONTROL_ID NUMBER(9,0)  NOT NULL,
    CONSTRAINT INITIAL_PAYLOAD_PK PRIMARY KEY (ID),
    CONSTRAINT INITIAL_PAYLOAD_UK1 UNIQUE (BALLOT_BOX_ID, ELECTION_EVENT_ID),
    CONSTRAINT INITIAL_PAYLOAD_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);
CREATE SEQUENCE INITIAL_PAYLOAD_SEQ;

CREATE TABLE SHUFFLE_PAYLOAD
(
    ID                 INTEGER NOT NULL,
    BALLOT_BOX_ID      VARCHAR2(255 CHAR) NOT NULL,
    ELECTION_EVENT_ID  VARCHAR2(255 CHAR) NOT NULL,
    NODE_ID            NUMBER(1,0) NOT NULL,
    PAYLOAD            BLOB    NOT NULL,
    INITIAL_PAYLOAD_FK_ID INTEGER NOT NULL,
    CHANGE_CONTROL_ID  NUMBER(9,0)  NOT NULL,
    CONSTRAINT SHUFFLE_PAYLOAD_PK PRIMARY KEY (ID),
    CONSTRAINT SHUFFLE_PAYLOAD_UK1 UNIQUE (BALLOT_BOX_ID, ELECTION_EVENT_ID, NODE_ID),
    CONSTRAINT SHUFFLE_PAYLOAD_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0),
    FOREIGN KEY (INITIAL_PAYLOAD_FK_ID) REFERENCES INITIAL_PAYLOAD (ID)
);

CREATE SEQUENCE SHUFFLE_PAYLOAD_SEQ;
