/*
 * (c) Copyright 2022 Swiss Post Ltd.
 */
package ch.post.it.evoting.domain;

public enum Context {
	MIXING_CONFIGURATION_SETUP_TALLY_CCM,
	MIXING_TALLY_MIX_DEC_ONLINE,
	CONFIGURATION_RETURN_CODES_GEN_ENC_LONG_CODE_SHARES,
	CONFIGURATION_RETURN_CODES_GEN_KEYS_CCR,
	VOTING_RETURN_CODES_CREATE_LCC_SHARE,
	VOTING_RETURN_CODES_CREATE_LVCC_SHARE,
	VOTING_RETURN_CODES_PARTIAL_DECRYPT_PCC,
	CONFIGURATION_ELECTION_CONTEXT
}
